# Generated by Django 5.1.4 on 2025-02-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='telegram_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
